### ISSUE TITLE
Denial of Service risk

### ISSUE THREAD

**Issue by brianchirls** [npm/npm-profile#4]
This package depends on an old version of make-fetch-happen (^2.5.0), which in turn depends on an old version of https-proxy-agent with the following security risk:
https://nodesecurity.io/advisories/593

make-fetch-happen has been fixed as of [v3.0.0](https://github.com/zkat/make-fetch-happen/commit/48cb3982d81467e816ef44d4e3becbfb08b81762). Alternatively, the refactor in #3 removes the dependency altogether.

**Comment by zkat** [comment]
#3 doesn't remove m-f-h. It just moves it down the stack. It _does_ use the latest m-f-h, though, so it'll still address this vuln. :)
