### ISSUE TITLE
Create token from cli is not working

### ISSUE THREAD

**Issue by AVVS** [npm/npm-profile#5]
https://github.com/npm/npm-profile/blob/latest/lib/index.js#L239

password is part of body and not auth object in the fetchJSON method, so result is the following:

```
(master) $ npm token create
npm password: 
npm ERR! code EAUTHUNKNOWN
npm ERR! Unable to authenticate, need: Basic, Bearer
```

**Comment by govstack** [comment]
Also, if you specify a token in the `opts` object as your means of auth, why is the `password` a mandatory API requirement?

e.g.

```javascript
const newToken = await profile.createToken("", READ_ONLY, [], {token: "some-npm-token"});
```

**Comment by wraithgar** [comment]
Closing due to age. If this is still an issue w/ npm-profile please reopen with details.
